In [ ]:
import torch

## Create a random tensor with shape (7,7)

In [ ]:
tensor = torch.rand(7,7)
tensor

tensor([[0.3597, 0.9441, 0.7150, 0.6637, 0.6438, 0.1711, 0.4366],
        [0.4534, 0.2197, 0.2294, 0.9724, 0.2139, 0.7856, 0.4940],
        [0.3943, 0.2098, 0.4029, 0.1547, 0.6766, 0.3427, 0.7940],
        [0.9563, 0.1831, 0.3761, 0.9115, 0.5810, 0.3467, 0.4532],
        [0.1597, 0.0170, 0.9896, 0.4414, 0.1447, 0.8033, 0.0644],
        [0.4010, 0.8378, 0.5403, 0.1819, 0.1815, 0.0104, 0.4148],
        [0.8220, 0.3563, 0.2512, 0.6388, 0.7771, 0.2726, 0.7949]])

## Perform a matrix multiplication with the above tensor of tensor with shape(1,7)

In [ ]:
tensor2 = torch.rand(1,7)
tensor.shape, tensor2.shape

(torch.Size([7, 7]), torch.Size([1, 7]))

In [ ]:
mult = torch.matmul(tensor, tensor2.T)
mult, mult.shape

(tensor([[2.1388],
         [1.4539],
         [1.6272],
         [1.8728],
         [1.2705],
         [1.2979],
         [2.0165]]),
 torch.Size([7, 1]))

## Set the random seed 0 and do the operations again

In [ ]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(7,7)

torch.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(1,7)

tensor.shape, tensor2.shape

(torch.Size([7, 7]), torch.Size([1, 7]))

In [ ]:
mult = torch.matmul(tensor, tensor2.T)
mult, mult.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

## Random seed 1234 for GPU equivalent tensor

In [ ]:
import torch
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(7,7, device = 'cuda')
tensor

tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903],
        [0.3394, 0.5451, 0.7312, 0.3864, 0.5959, 0.7578, 0.2126],
        [0.7198, 0.9845, 0.5518, 0.0981, 0.0582, 0.5839, 0.1083],
        [0.9461, 0.3170, 0.8328, 0.6676, 0.2886, 0.9022, 0.8115],
        [0.1784, 0.9534, 0.1486, 0.3882, 0.7977, 0.1752, 0.5777],
        [0.1949, 0.8499, 0.3125, 0.2156, 0.0383, 0.4934, 0.3138],
        [0.3121, 0.5664, 0.1266, 0.7097, 0.0040, 0.5147, 0.2811]],
       device='cuda:0')

In [ ]:
tensor.device

device(type='cuda', index=0)

## Create two random tensors both using the Random seed 1234 of GPU

In [ ]:
torch.manual_seed(RANDOM_SEED)
tensor1 = torch.rand(2,3, device = 'cuda')

torch.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(2,3, device = 'cuda')

tensor1.shape, tensor2.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

## Matrix Multiplication of the above two tensors

In [ ]:
mult = torch.matmul(tensor1, tensor2.T)
mult, mult.shape

(tensor([[0.9792, 0.8358],
         [0.8358, 1.4578]], device='cuda:0'),
 torch.Size([2, 2]))

## Find the maximum and the minimum values of the output 7

In [ ]:
print(tensor1.max())
print(tensor1.min())

print(tensor2.max())
print(tensor2.min())

tensor(0.9737, device='cuda:0')
tensor(0.1272, device='cuda:0')
tensor(0.9737, device='cuda:0')
tensor(0.1272, device='cuda:0')


## Find the maximum and minimum index of the above tensors

In [ ]:
print(tensor1.argmax())
print(tensor1.argmin())

print(tensor2.argmax())
print(tensor2.argmin())

tensor(5, device='cuda:0')
tensor(0, device='cuda:0')
tensor(5, device='cuda:0')
tensor(0, device='cuda:0')


## Create a Random tensor with shape(1,1,1,10) and then then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [ ]:
import torch

In [ ]:
tensor = torch.rand(1,1,1,10)
tensor

tensor([[[[0.3029, 0.3976, 0.3222, 0.4301, 0.7499, 0.9180, 0.6481, 0.4109,
           0.9707, 0.3571]]]])

In [ ]:
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)
new_tensor = tensor.squeeze()
new_tensor

tensor([0.3029, 0.3976, 0.3222, 0.4301, 0.7499, 0.9180, 0.6481, 0.4109, 0.9707,
        0.3571])

In [ ]:
tensor, tensor.shape

(tensor([[[[0.3029, 0.3976, 0.3222, 0.4301, 0.7499, 0.9180, 0.6481, 0.4109,
            0.9707, 0.3571]]]]),
 torch.Size([1, 1, 1, 10]))

In [ ]:
new_tensor, new_tensor.shape

(tensor([0.3029, 0.3976, 0.3222, 0.4301, 0.7499, 0.9180, 0.6481, 0.4109, 0.9707,
         0.3571]),
 torch.Size([10]))